name: Build RedisJSON DLL

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install make -y

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DREDISJSON_LIB_TYPE=dynamic

    - name: Build RedisJSON
      run: |
        cd build
        cmake --build . --config Release --target RedisJSON

    - name: Verify DLL file
      run: |
        dir build\Release\ /s | findstr "\.dll"
        if not exist "build\Release\RedisJSON.dll" exit 1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RedisJSON-dll
        path: build/Release/RedisJSON.dll
